name: tokenizr
version: 0.0.1+1
author: Axel Christ <adracus@gmail.com>
description: A package to tokenize an input string.
homepage: http://www.github.com/Adracus/tokenizr
documentation: http://www.github.com/Adracus/tokenizr
dependencies:
  logging: '>=0.9.1+1 <0.10.0'
dev_dependencies:
  unittest: any
